bug: erro no relacionamento envolvendo trajeto, motorista e carro
ImportError: cannot import name 'Motorista' from partially initialized module 'models.Motorista' (most likely due to a circular import) (\backend\models\Motorista.py)